export default {
	"Save Path":"保存経路",
	"Auto Start-up":"オートスタート",
	"Save":"保存",
	"Apps Settings":"アプリ設定",
	"Information":"インフォメーション",
	"Email":"Email",
	"Name":"お名前",
	"Country":"国籍",
	"Created":"作成",
	"Last Login":"前回のログイン",
	"Language":"言語",
	"Do you want to logout?":"ログアウトしますか？",
	"Empty":"空",
	"DentalDB.exe Path":"DentalDB.exe パス",
	"Code":"コード",
	"Password":"パスワード",
	"Require email":"メールが必要",
	"This email does not exist.":"このメールは存在しません。",
	"An error has occurred.":"エラーが発生しました。",
	"Failed to send email.":"メールの送信に失敗しました。",
	"Require code":"コードが必要",
	"The password has the following rules":"パスワードには以下のルールがあります",
	"At least 8 characters":"8 文字以上",
	"At least one uppercase letter":"少なくとも1つの大文字",
	"One or more lowercase letters":"1 つ以上の小文字",
	"One or more numbers":"1 つ以上の数字",
	"One or more special characters":"1 つ以上の特殊文字",
	"This email does not requested.":"このメールはリクエストされていません。",
	"The expiration time has expired.":"有効期限が切れています。",
	"Password Changed":"パスワード変更済み",
	"Your password has been changed.":"パスワードが変更されました。",
	"Login":"ログイン",
	"Forgot Password?":"パスワードをお忘れですか ？",
	"Enter your email to reset your password.":"メールアドレスを入力してパスワードをリセットしてください。",
	"Submit":"送信",
	"Cancel":"キャンセル",
	"Fail Register":"登録失敗",
	"Please sign up via another email.":"別のメールでサインアップしてください。",
	"Registration failed.":"登録に失敗しました。",
	"Please try again from the beginning.":"最初からやり直してください。",
	"Restart":"再起動",
	"Email already exists.":"メールは既に存在します。",
	"Your account has been created.":"あなたのアカウントが作成されました。",
	"An authentication email was sent to the generated email." : "生成された 電子メールに認証電子メールが送信されました。'",
	"Please proceed with the login after completing the mail authentication.":"メール認証完了後、ログインしてください。",
	"Already have an account?":"すでにアカウントをお持ちですか？",
	"Sign in now.":"今すぐログインしてください。",
	"User Information":"ユーザー情報",
	"Prev":"前へ",
	"Next":"次",
	"Please check.":"チェックしてください。",
	"Institute Information":"研究所情報",
	"Select Your Region & Account Type.":"地域とアカウントの種類を選択します。",
	"Welcome to RAYTeams.":"RAYteamsへようこそ。",
	"Sign up":"サインアップ",
	"Korean":"韓国語",
	"Please enter a search keyword.":"検索キーワードを入力してください。",
	"The search keyword must be at least 2 characters long.":"検索キーワードは 2 文字以上にする必要があります。",
	"Search...":"探す...",
	"Select":"選択する",
	"address":"住所",
	"The original region and address are different. You agree that use is not permitted outside of your chosen region.":"元の地域と住所が異なります。選択した地域以外での使用は許可されていないことに同意するものとします。",
	"I read the description well.":"説明をよく読みました。",
	"If you have read the description, please check it.":"説明をお読みになった方は、ご確認ください。",
	"Tel":"電話",
	"Save Changes":"変更内容を保存",
	"When associated with a single institute, the information is shared directly with that institute.":"単一の機関に関連付けられている場合、情報はその機関と直接共有されます。",
	"address extra":"アドレス追加",
	"Zip Code":"郵便番号",
	"Upload Project":"プロジェクトのアップロード",
	"Missing DentalDB.exe file path":"DentalDB.exe ファイル パスがありません",
	"Under Settings, select the correct setting for DentalDB file path.":"[設定] で、DentalDB ファイル パスの正しい設定を選択します。",
	"Go to Setting":"設定に移動",
	"Drop the files here ...":"ここにファイルをドロップしてください...",
	"Yes":"はい",
	"No":"いいえ",
	"Add":"追加",
	"Apps":"アプリ",
	"App Information":"アプリ情報",
	"Require RAYTeams":"RAYTeams が必要",
	"Please update RAYTeams.":"RAYTeams をアップデートしてください。",
	"Settings":"設定",
}