export default {
	"Save Path":"Сохранить Путь",
	"Auto Start-up":"Автозапуск",
	"Save":"Сохранить",
	"Apps Settings":"Настройки Приложений",
	"Information":"Информация",
	"Email":"Эл. адрес",
	"Name":"Имя",
	"Country":"Страна",
	"Created":"Созданный",
	"Last Login":"Последний Вход",
	"Language":"Язык",
	"Do you want to logout?":"Вы хотите выйти?",
	"Empty":"Пустой",
	"DentalDB.exe Path":"Путь DentalDB.exe",
	"Code":"Код",
	"Password":"Пароль",
	"Require email":"Требование эл. адрес",
	"This email does not exist.":"Эл. адрес не существует.",
	"An error has occurred.":"Произошла ошибка.",
	"Failed to send email.":"Не удалось отправить эл. письмо.",
	"Require code":"Требования кода",
	"The password has the following rules":"Пароль имеет следующие правила",
	"At least 8 characters":"Не менее 8 символов",
	"At least one uppercase letter":"Хотя бы одна заглавная буква",
	"One or more lowercase letters":"Одна или несколько строчных букв",
	"One or more numbers":"Одно или несколько чисел",
	"One or more special characters":"Один или несколько специальных символов",
	"This email does not requested.":"Это эл. письмо не запрашивается.",
	"The expiration time has expired.":"Срок годности истек.",
	"Password Changed":"Пароль Изменен",
	"Your password has been changed.":"Ваш пароль был изменен.",
	"Login":"Авторизоваться",
	"Forgot Password ?":"Забыляи пароль ?",
	"Enter your email to reset your password.":"Введите Ваш эл. адрес, чтобы сбросить пароль.",
	"Submit":"Предоставлять",
	"Cancel":"Отмена",
	"Fail Register":"Ошибка регистрации",
	"Please sign up via another email.":"Пожалуйста, зарегистрируйтесь через другой эл. адрес.",
	"Registration failed.":"Регистрация не удалась.",
	"Please try again from the beginning.":"Пожалуйста, попробуйте еще раз с самого начала.",
	"Restart":"Перезапущение",
	"Email already exists.":"Эл. адрес уже существует.",
	"Your account has been created.":"Ваш аккаунт был создан.",
	"An authentication email was sent to the generated email.":"Электронное письмо для аутентификации было отправлено на сгенерированный адрес эл. почты email.",
	"Please proceed with the login after completing the mail authentication.":"Пожалуйста, войдите в систему после завершения проверки подлинности почты.",
	"Already have an account?":"У вас уже есть аккаунт?",
	"Sign in now.":"Войдите сейчас.",
	"User Information":"Информация о пользователе",
	"Prev":"Пред.",
	"Next":"След.",
	"Please check.":"Пожалуйста, проверьте.",
	"Institute Information":"Информация об Учереждении",
	"Select Your Region & Account Type.":"Выберите свой регион и тип учетной записи.",
	"Welcome to RAYTeams.":"Добро пожаловать в RAY Teams.",
	"Sign up":"Подписаться",
	"Korean":"Корейский",
	"Please enter a search keyword.":"Пожалуйста, введите ключевое слово для поиска.",
	"The search keyword must be at least 2 characters long.":"Ключевое слово для поиска должно быть не менее 2 символов.",
	"Search...":"Поиск...",
	"Select":"Выбрать",
	"address":"адрес",
	"The original region and address are different. You agree that use is not permitted outside of your chosen region.":"Исходный регион и адрес отличаются. Вы соглашаетесь с тем, что использование запрещено за пределами выбранного вами региона.",
	"I read the description well.":"Я досконально прочитал(а) описание.",
	"If you have read the description, please check it.":"Если вы прочитали описание, пожалуйста, отметьте.",
	"Tel":"Тел.",
	"Save Changes":"Сохранить изменения",
	"When associated with a single institute, the information is shared directly with that institute.":"Когда система связана с одним учреждением, информация передается непосредственно этому учреждению. ",
	"address extra":"дополнительный адрес",
	"Zip Code":"Почтовый индекс",
	"Upload Project":"Загрузить проект",
	"Missing DentalDB.exe file path":"Отсутствует путь к файлу DentalDB.exe",
	"Under Settings, select the correct setting for DentalDB file path.":"В разделе «Настройки» выберите правильный путь к файлу DentalDB.",
	"Goto Setting":"Перейти к настройке",
	"Drop the files here ...":"Вставьте файлы сюда...",
	"Yes":"Да",
	"No":"Нет",
	"Add":"Добавить",
	"Apps":"Приложения",
	"App Information":"Информация о приложении",
	"Require RAYTeams":"Требование RAYTeams",
	"Please update RAYTeams.":"Пожалуйста, обновите RAYTeams.",
	"Settings":"Настройки"
}